<?PHP
/**
* RADNDAR: Combines RADNELAC and N-Darcale Calendars
* Author: Thomas Wright aka ender / kryp7k
* Organization: Phobos Technologies LLC.
* License: GNU GPLv3 - GNU General Public License v3.0
*
* Thanks to Jake Bellacera - from whom I borrowed the ICS.inc class
* for injecting these whacky cals straight straight into the vein.
*   https://gist.github.com/jakebellacera
*   https://gist.github.com/jakebellacera/635416
*
*/
class Radndar{
  // to be further revised and cleaned up when I have a second ...
}
